In [44]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [77]:
from src.collect import fetch_truspilot_reviews4, testing

#fetch_truspilot_reviews4(site="www.oscaro.com",nb_pages=3)
testing()

ImportError: cannot import name 'display' from 'IPython.core.display' (c:\Users\lione\Documents\GitHub\Supply-Chain-mlops\.ml\Lib\site-packages\IPython\core\display.py)

In [13]:
import pandas as pd
from pathlib import Path
import csv

def get_avis(id):
    avisF = Path(f"../data/avis_{id}k.csv")
    if avisF.exists():
        return pd.read_csv(avisF,sep=";")

df=pd.concat([get_avis(40),get_avis(28)])

nodupkeys=["auteur","note","titre","commentaire","date_experience","texteServiceReply","dateServiceReply","dataServiceReply"]
df = df.drop(columns=["url"])
df = df.sort_values(by=nodupkeys)
df = df.drop_duplicates(subset=nodupkeys)
display(df.head())

df.info(memory_usage="deep")
avis45=Path("../data/avis_45k.csv")
df.to_csv(avis45, index=None,sep=";",quoting=csv.QUOTE_ALL)

,auteur,note,titre,commentaire,date_experience,date_avis,texteServiceReply,dateServiceReply,dataServiceReply
3659,"""Bruno "" ""De Oliveira """,5,Je ne connais pas votre entreprise mais…,Je ne connais pas votre entreprise mais je tro...,"January 22, 2026","Jan 22, 2026",Reply from Oscaro,"Jan 26, 2026","Bonjour Bruno, Nous sommes ravis d'apprendre q..."
22746,"""Carole "" ""LEFEBVRE """,1,Ma commande du 4 mars a été désastreuse…,Ma commande du 4 mars a été désastreuse !!! J’...,"March 4, 2026","Mar 12, 2026",NaN,NaN,NaN
11629,"""Lyvio "" ""CLOVIS """,2,Certaines pièces ne correspondait pas à…,Certaines pièces ne correspondait pas à mon vé...,"November 8, 2025","Nov 12, 2025",Reply from Oscaro,"Nov 12, 2025","Bonjour Lyvio, Je comprends que la situation s..."
5652,"""Patrick "" ""Cron """,5,Livraison rapide et gratuite,NaN,"December 26, 2025","Dec 27, 2025",Reply from Oscaro,"Jan 6, 2026","Bonjour Nicolas , Nous sommes ravis que vous a..."
31160,"""Sandrine "" SENDRA",5,Parfait,"Parfait, livraison dans les temps. Pièce adaptée.","June 7, 2025","Jun 7, 2025",NaN,NaN,NaN

<class 'pandas.DataFrame'>
Index: 45839 entries, 3659 to 33678
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   auteur             45839 non-null  str
 1   note               45839 non-null  int64
 2   titre              45839 non-null  str
 3   commentaire        41660 non-null  str
 4   date_experience    45839 non-null  str
 5   date_avis          45839 non-null  str
 6   texteServiceReply  38741 non-null  str
 7   dateServiceReply   38741 non-null  str
 8   dataServiceReply   38741 non-null  str
dtypes: int64(1), str(8)
memory usage: 44.1 MB

In [19]:
import pandas as pd
from pathlib import Path
import csv

avis45=Path("../data/avis_45k.csv")
df45=pd.read_csv(avis45,sep=";",quoting=csv.QUOTE_ALL)


df45['date_experience']  = pd.to_datetime(df45['date_experience'], errors='coerce')
df45['date_avis']        = pd.to_datetime(df45['date_avis'], errors='coerce')
df45['dateServiceReply'] = pd.to_datetime(df45['dateServiceReply'], errors='coerce')

df45['Period']= 'P'+df45['date_experience'].dt.isocalendar().year.astype(str) + \
     df45['date_experience'].dt.isocalendar().week.astype(str).str.zfill(2)

df45['YearMonth_experience']  = df45['date_experience'].dt.to_period('M')
df45['YearMonth_avis']        = df45['date_avis'].dt.to_period('M')
df45['YearMonthServiceReply'] = df45['dateServiceReply'].dt.to_period('M')


df45

,auteur,note,titre,commentaire,date_experience,date_avis,texteServiceReply,dateServiceReply,dataServiceReply,Period,YearMonth_experience,YearMonth_avis,YearMonthServiceReply
0,"""Bruno "" ""De Oliveira """,5,Je ne connais pas votre entreprise mais…,Je ne connais pas votre entreprise mais je tro...,2026-01-22,2026-01-22,Reply from Oscaro,2026-01-26,"Bonjour Bruno, Nous sommes ravis d'apprendre q...",P202604,2026-01,2026-01,2026-01
1,"""Carole "" ""LEFEBVRE """,1,Ma commande du 4 mars a été désastreuse…,Ma commande du 4 mars a été désastreuse !!! J’...,2026-03-04,2026-03-12,NaN,NaT,NaN,P202610,2026-03,2026-03,NaT
2,"""Lyvio "" ""CLOVIS """,2,Certaines pièces ne correspondait pas à…,Certaines pièces ne correspondait pas à mon vé...,2025-11-08,2025-11-12,Reply from Oscaro,2025-11-12,"Bonjour Lyvio, Je comprends que la situation s...",P202545,2025-11,2025-11,2025-11
3,"""Patrick "" ""Cron """,5,Livraison rapide et gratuite,NaN,2025-12-26,2025-12-27,Reply from Oscaro,2026-01-06,"Bonjour Nicolas , Nous sommes ravis que vous a...",P202552,2025-12,2025-12,2026-01
4,"""Sandrine "" SENDRA",5,Parfait,"Parfait, livraison dans les temps. Pièce adaptée.",2025-06-07,2025-06-07,NaN,NaT,NaN,P202523,2025-06,2025-06,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45834,𝑲𝒂𝒚𝒊𝒎 ALI TOIHIR,1,Mauvais matériel vendu,Mauvais matériel vendu,2026-03-17,2026-03-24,Reply from Oscaro,2026-03-26,"Bonjour M., Nous souhaitons avoir plus d'infor...",P202612,2026-03,2026-03,2026-03
45835,👍,5,Ok parfait,Belle expérience,2025-04-19,2025-04-20,Reply from Oscaro,2025-04-29,"Bonjour M, Merci beaucoup pour votre avis posi...",P202516,2025-04,2025-04,2025-04
45836,👍,5,Produit de qualité très satisfaisant et…,Produit de qualité très satisfaisant et livrai...,2025-12-12,2025-12-21,Reply from Oscaro,2025-12-24,"Bonjour Francois, Nous sommes ravis que notre ...",P202550,2025-12,2025-12,2025-12
45837,🤝,5,🌟🌟🌟🍾👌👍🫶🫶🫶🌹,NaN,2025-05-18,2025-05-18,NaN,NaT,NaN,P202520,2025-05,2025-05,NaT
45838,🫡,5,Rapide,"Rapide, Super bien",2025-05-21,2025-05-23,NaN,NaT,NaN,P202521,2025-05,2025-05,NaT

In [17]:
df = pd.DataFrame({
    'date': pd.to_datetime(['2021-01-01', '2024-03-15', '2024-12-30'])
})

df['periode'] = (
    df['date'].dt.isocalendar().year.astype(str) +
    df['date'].dt.isocalendar().week.astype(str).str.zfill(2)
)

df

        date periode
0 2021-01-01  202053
1 2024-03-15  202411
2 2024-12-30  202501

In [41]:
from datetime import datetime, timedelta
if False:
    for p in range(1000):
        d =  datetime.now() - timedelta(days=p)
        print(d, "P"+str(d.isocalendar().year) + str(d.isocalendar().week).zfill(2) )
pd.set_option("display.max_rows",500)
pd.set_option('max_colwidth', 400)


calendar = pd.DataFrame({"date":[datetime.now() - timedelta(days=p-3650) for p in range(19800)]})
calendar["Period"] ='P'+calendar['date'].dt.isocalendar().year.astype(str) + \
     calendar['date'].dt.isocalendar().week.astype(str).str.zfill(2)   

calendar[ calendar.Period.str.endswith("53") ]

                            date   Period
1211  2033-01-02 15:45:11.664819  P203253
1212  2033-01-01 15:45:11.664821  P203253
1213  2032-12-31 15:45:11.664822  P203253
1214  2032-12-30 15:45:11.664824  P203253
1215  2032-12-29 15:45:11.664826  P203253
1216  2032-12-28 15:45:11.664827  P203253
1217  2032-12-27 15:45:11.664829  P203253
3402  2027-01-03 15:45:11.669363  P202653
3403  2027-01-02 15:45:11.669365  P202653
3404  2027-01-01 15:45:11.669366  P202653
3405  2026-12-31 15:45:11.669369  P202653
3406  2026-12-30 15:45:11.669371  P202653
3407  2026-12-29 15:45:11.669373  P202653
3408  2026-12-28 15:45:11.669374  P202653
5593  2021-01-03 15:45:11.673732  P202053
5594  2021-01-02 15:45:11.673734  P202053
5595  2021-01-01 15:45:11.673735  P202053
5596  2020-12-31 15:45:11.673737  P202053
5597  2020-12-30 15:45:11.673739  P202053
5598  2020-12-29 15:45:11.673740  P202053
5599  2020-12-28 15:45:11.673742  P202053
7420  2016-01-03 15:45:11.677082  P201553
7421  2016-01-02 15:45:11.677083  P201553
7422  2016-01-01 15:45:11.677085  P201553
7423  2015-12-31 15:45:11.677087  P201553
7424  2015-12-30 15:45:11.677088  P201553
7425  2015-12-29 15:45:11.677090  P201553
7426  2015-12-28 15:45:11.677091  P201553
9611  2010-01-03 15:45:11.680801  P200953
9612  2010-01-02 15:45:11.680803  P200953
9613  2010-01-01 15:45:11.680805  P200953
9614  2009-12-31 15:45:11.680806  P200953
9615  2009-12-30 15:45:11.680808  P200953
9616  2009-12-29 15:45:11.680809  P200953
9617  2009-12-28 15:45:11.680811  P200953
11438 2005-01-02 15:45:11.684291  P200453
11439 2005-01-01 15:45:11.684292  P200453
11440 2004-12-31 15:45:11.684294  P200453
11441 2004-12-30 15:45:11.684295  P200453
11442 2004-12-29 15:45:11.684297  P200453
11443 2004-12-28 15:45:11.684298  P200453
11444 2004-12-27 15:45:11.684300  P200453
13629 1999-01-03 15:45:11.688784  P199853
13630 1999-01-02 15:45:11.688786  P199853
13631 1999-01-01 15:45:11.688788  P199853
13632 1998-12-31 15:45:11.688790  P199853
13633 1998-12-30 15:45:11.688792  P199853
13634 1998-12-29 15:45:11.688794  P199853
13635 1998-12-28 15:45:11.688796  P199853
15820 1993-01-03 15:45:11.695544  P199253
15821 1993-01-02 15:45:11.695546  P199253
15822 1993-01-01 15:45:11.695549  P199253
15823 1992-12-31 15:45:11.695551  P199253
15824 1992-12-30 15:45:11.695553  P199253
15825 1992-12-29 15:45:11.695556  P199253
15826 1992-12-28 15:45:11.695558  P199253
17647 1988-01-03 15:45:11.699913  P198753
17648 1988-01-02 15:45:11.699914  P198753
17649 1988-01-01 15:45:11.699916  P198753
17650 1987-12-31 15:45:11.699917  P198753
17651 1987-12-30 15:45:11.699919  P198753
17652 1987-12-29 15:45:11.699921  P198753
17653 1987-12-28 15:45:11.699922  P198753